#!/bin/bash
# grep

attrs="-rn";
version=$(grep -V | grep -o '[0-9]\.[0-9.]\{3,\}');
vercomp $version '2.5.1';
if [[ $? == 1 ]]; then
    node_exclusions="--exclude-dir=node_modules --exclude-dir=dist --exclude-dir=cdn";
    attrs="$attrs -I --exclude-dir=.git --exclude-dir=local --exclude-dir=.build --exclude-dir=cover_db $node_exclusions";
fi;
grep $attrs "$@"
