#!/bin/bash
sess=$1
tmux has -t $1 2> /dev/null
if [[ $? -ne 0 ]]; then
    tmuxlogdir=$HOME/.jtmux-logs
    mkdir -p $tmuxlogdir
    # for tracking crashes, add -v for full output
    cd $tmuxlogdir && tmux -v new -d -s $sess
    tmux new-w
    tmux new-w
    tmux new-w
    tmux new-w
fi
jtmux-windows $sess
tmux a -t $sess
